packaging_format = 2

id = "phpipam"
name = "phpIPAM"
description.en = "Web IP address management application"
description.fr = "Application web de gestion d'adresses IP"

version = "1.19.8~ynh2"

maintainers = []

[upstream]
license = "GPL-3.0-only"
website = "https://phpipam.net"
demo = "http://demo.phpipam.net"
admindoc = "https://phpipam.net/documents/"
code = "https://github.com/phpipam/phpipam"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/phpipam"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/phpipam/phpipam/archive/refs/tags/v1.19.008.tar.gz"
        sha256 = "dcb2c3e7e627d5d48380a478d9c8281c34734885d4adeb4e31d3f9aebd54c347"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"

    [resources.apt]
    packages = "mariadb-server, php8.2-gmp, php8.2-mysql, php8.2-ldap, php8.2-gd, php8.2-opcache, php8.2-fileinfo, php8.2-intl, php8.2-cli, php8.2-mbstring, php8.2-xml"

    [resources.database]
    type = "mysql"
