#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove the dedicated PHP-FPM config
ynh_config_remove_phpfpm

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
